import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/navbar";

import { Ysabeau_Infant } from "next/font/google";

const ysabeau = Ysabeau_Infant({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hom0rics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={ysabeau.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
