import type { Metadata } from "next";
import "./globals.css";
import { Ysabeau_Infant } from "next/font/google";

// * components
import Navbar from "./(components)/navbar";
import { ReduxProvider } from "./Redux/provider";

const ysabeau = Ysabeau_Infant({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hom0rics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={ysabeau.className}>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
